commerce_payment.commerce_payment_gateway.plugin.wire_transfer_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    instructions:
      type: text_format
      label: 'Payment instructions'
      translatable: true
